### ISSUE TITLE
Malformed packet

### ISSUE THREAD

**Issue by bedenko** [Jerome-PS/JN516xSniffer#3]
I use Tradfri bulb with 5 button remote. If i press sync button in the back of the remote, i get error "Frame X too long (4063232 bytes)".

I am attaching few screenshots of packed captured before button press:

![screenshot_2018-02-04_16-19-08](https://user-images.githubusercontent.com/7294788/35779047-3e44a81a-09c7-11e8-9628-d7816d342f3a.png)

![screenshot_2018-02-04_16-33-05](https://user-images.githubusercontent.com/7294788/35779172-1c5db294-09c9-11e8-8936-6f1c3300b7bf.png)

**Comment by Jerome-PS** [comment]
Hi Ivo,
Nice to have people using this software ;D

Could you run the same capture using the following command (you might have to change the **ttyUSB0** part...):
```
stty -F /dev/ttyUSB0 38400 raw ignbrk -onlcr -iexten -echo -echoe -echok -echoctl -echoke & cat /dev/ttyUSB0 | tee /tmp/sf.bin > /tmp/sharkfifo
```
And send me the **/tmp/sf.bin** log?

**Comment by bedenko** [comment]
Sure. Here you go:

https://drive.google.com/file/d/1V9LXHhbobk9Jj3Hp0_0ioupyHoxkgMpr/view?usp=sharing

**Comment by Jerome-PS** [comment]
I can't get your file:
```
{"success":false,"error":404,"message":"Not Found"}
```

**Comment by bedenko** [comment]
Sorry, it is on google drive now. (Link updated)

**Comment by Jerome-PS** [comment]
Which hardware are you using as a sniffer?

**Comment by bedenko** [comment]
Xiaomi temperature/humidity sensor v1

**Comment by bedenko** [comment]
I have also tried to modify source with 
```
LED_PIN_BIT  (1 << 1)
MAIN_PIN_BIT (1 << 5)
```
since DIO1=led and DIO5=button,
but without success so far.

**Comment by Jerome-PS** [comment]
I think I'll need some additional trace...
Can you try with this firmware, it will give you a cleartext trace on the serial port at 38400 Baud.

[JN516xSniffer_JN5169.bin.zip](https://github.com/Jerome-PS/JN516xSniffer/files/1693263/JN516xSniffer_JN5169.bin.zip)

**Comment by bedenko** [comment]
One of those two packets (or both) should cause this:
```
Cleartext log start
   5.8210340:New packet
	            Packet good [  1] : yes
	              u16FrameControl : 0xc801
	        u16SourceShortAddress : 0xfea8
	   u16DestinationShortAddress : 0xffff
	     u64SourceExtendedAddress : 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
	u64DestinationExtendedAddress : 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
	               u16SourcePanID : 0x8899
	          u16DestinationPanID : 0xffff
	              u8PayloadLength :   16
	0x0b 0x00 0x0b 0x00 0x10 0x5e 0xc0 0x11 0x9a 0x00 0x94 0xbe 0x25 0x49 0x02 0x13 
	              u16FrameControl : 0xc801
	                     u8Energy :   0x8a
	                        u8SQI :   0xff
	             u8SequenceNumber :   0x30
	                        u8LQI :   0x82
	                       u8RSSI :   0x42

85.3009500:New packet
	            Packet good [  1] : yes
	              u16FrameControl : 0xc801
	        u16SourceShortAddress : 0xfea8
	   u16DestinationShortAddress : 0xffff
	     u64SourceExtendedAddress : 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
	u64DestinationExtendedAddress : 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
	               u16SourcePanID : 0x8899
	          u16DestinationPanID : 0xffff
	              u8PayloadLength :   16
	0x0b 0x00 0x0b 0x00 0x10 0x5e 0xc0 0x11 0xa8 0x00 0x7e 0xe5 0x30 0xbc 0x02 0x13 
	              u16FrameControl : 0xc801
	                     u8Energy :   0x7e
	                        u8SQI :   0xfb
	             u8SequenceNumber :   0x3e
	                        u8LQI :   0x76
	                       u8RSSI :   0x3e

```

**Comment by Jerome-PS** [comment]
Hi,
I see what it is, the code did not take into account long addresses...
Could you try again with this firmware?
Keep me updated if it improves things.
[JN516xSniffer_JN5169.bin.zip](https://github.com/Jerome-PS/JN516xSniffer/files/1693326/JN516xSniffer_JN5169.bin.zip)

**Comment by bedenko** [comment]
Tried the last firmware, but unfortunately the problem persist.
Only that now the error throws negative number:
```Frame 4 too long (-11941887 bytes)```

**Comment by Jerome-PS** [comment]
Could you send me the new sf.bin?
I'm sorry, I don't see those frames on my network, so I have to rely on you to test it out...

**Comment by bedenko** [comment]
Sure thing. Here is the new sf.bin:

https://drive.google.com/file/d/1in68_uBj0AXNeOljCFAQOwfkVUOOWTkH/view?usp=sharing

**Comment by Jerome-PS** [comment]
Well, this frame should be OK now, I hope it doesn't break others, well, let's test!
[JN516xSniffer_JN5169.bin 2.zip](https://github.com/Jerome-PS/JN516xSniffer/files/1693348/JN516xSniffer_JN5169.bin.2.zip)

**Comment by Jerome-PS** [comment]
Could you also try the latest firmware I check in:
[bin folder](https://github.com/Jerome-PS/JN516xSniffer/tree/master/bin)

**Comment by bedenko** [comment]
Three captures for your first comment:
https://drive.google.com/file/d/1Rc7ZjfTiQEXSe1tA1NmijyK1nfXVKlM2/view
three captures for latest commit:
https://drive.google.com/file/d/1s_mf033ZKBJhX-pMtoyzcMPCMd-cNMdX/view

**Comment by Jerome-PS** [comment]
Hi,
Could you try with the binary from tonight?
I think I made progress...

**Comment by bedenko** [comment]
Success! 
No more crashing:

https://drive.google.com/file/d/1g5xl_mWbBDfWzLqWsrIMhW_saDDlIQTD/view?usp=sharing

**Comment by Jerome-PS** [comment]
Nice!
Thank you for all the testing!
