### ISSUE TITLE
Timing is not right

### ISSUE THREAD

**Issue by KiwiHC16** [Jerome-PS/JN516xSniffer#4]
Salut Jerome-PS,

De temps en temps le champ Time ne semble pas correct. Est en relation avec mon autre problème https://github.com/KiwiHC16/Butineuse/issues/2, je ne sais pas encore dire.

![capture d ecran 2018-02-09 a 19 32 12](https://user-images.githubusercontent.com/8549674/36044515-379fe780-0dd3-11e8-93f1-ff9a83d902fe.png)

![capture d ecran 2018-02-09 a 19 34 44](https://user-images.githubusercontent.com/8549674/36044550-4e07864a-0dd3-11e8-867c-0ee70cb79c1e.png)

Est ce un probleme de buffer, le fait que le debug soit sur UART1 ? Aucune piste pour l'instant.

Ceci explique pourquoi je ne vois pas tous les ACK niveau MAC et que certains paquets me semblaient ne pas être transmis, en fait je le vois de temps en temps du fait du timing je pense. J'étais donc sur la mauvaise piste.

Les drop de paquets est probablement la source de tous les problèmes.

**Comment by Jerome-PS** [comment]
Salut,

Il y avait bien un bug dans le calcul de la date... C'est corrigé.
J'ai aussi ajouté de la couleur pour les trames ZCL et link status dans le fichier zb.lua.

Merci pour le bugreport.

**Comment by KiwiHC16** [comment]
Salut,

Trop fort !!!

Il faut que je teste maintenant.

Ben

**Comment by KiwiHC16** [comment]
As tu une idée pour KiwiHC16/Butineuse#2 ?

**Comment by Jerome-PS** [comment]
Il faut que je fasse des essais...

**Comment by KiwiHC16** [comment]
Avec ma derniere version je vois passer les ACK MAC si le message percedent est tres court.
J’ai l’impression qu’on pert les paquets si un recoit un nouveau paquet zigbee pendant la transmission sur UART.
Je ne sais pas comment la reception zigbee et l envoie est géré en terme de multitâche, interruption,…
Je ne sais pas comment un paquet est considéré nouveau. Est ce qu’un nouveau paquet zigbee est mis dans une variable, puis écrasé a chaque nouvelle reception ? 
Comment ca se passe si on lit le paquet alors qu’un autre arrive ….
Je pense que le soucis est de ce cote la.
Ben
