### ISSUE TITLE
Binaire pour un JN5168

### ISSUE THREAD

**Issue by lboue** [Jerome-PS/JN516xSniffer#7]
Bonjour,

Serait-il possible de pré-compiler le binaire pour un JN5168 de la marque NXP ? Je voudrais tester sur un autre device. La référence du module est le MS5168-M05 de la société MESHREEN. 

Cordialement,

**Comment by Jerome-PS** [comment]
Bonjour,

Je viens de mettre une version binaire pour JN5168.

Jerome.
